pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('DOCKERHUB')
    }

    stages {
        stage('docker build') {
            steps {
                script {
                    echo "Building Docker image with version: 1.0.0-${BUILD_ID}"
                    //sh "docker build -f 02-primer-pipeline/Dockerfile -t caosbinario/homer_page:1.0.0-${BUILD_ID} 02-primer-pipeline"
                    bat "docker build -f 02-primer-pipeline/Dockerfile -t rdiosalf/jenkinscaos:1.0.0-${BUILD_ID} 02-primer-pipeline"

                }
            }
        }
        stage('docker login') {
            steps {
                script {
                    bat "docker login -u %DOCKERHUB_CREDENTIALS_USR% -p %DOCKERHUB_CREDENTIALS_PSW%"
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    //ojo los repos de docker hub no permiten rutas de tercer nivel 
                    //sh "docker push caosbinario/homer_page:1.0.0-${BUILD_ID}"
                    echo "pushear tengo que tener un usuario en docker hub.....${BUILD_ID}"
                    bat "docker push rdiosalf/jenkinscaos:1.0.0-${BUILD_ID}"
                }
            }
        }
    }
}