@Library('jenkinsLibstut') _
pipeline {
    agent any

    //credenciales de docker hub definidas a nivel general en jenkins 
    environment {
        DOCKERHUB_CREDENTIALS = credentials('DOCKERHUB')
    }

    stages {
        stage('docker build') {
            steps {
                script {
                    echo "usando libraries -Building Docker image with version: 1.0.0-${BUILD_ID}"
                    dockerLib.build(DockerfilePath: "02-primer-pipeline/Dockerfile",
                                    DockerImage: "rdiosalf/jenkinscaos:1.0.0-${BUILD_ID}",
                                    DockerContext: "02-primer-pipeline")
                }
            }
        }
        stage('docker login') {
            steps {
                script {
                    bat "docker login -u %DOCKERHUB_CREDENTIALS_USR% -p %DOCKERHUB_CREDENTIALS_PSW%"
                }
            }
        }
        stage('docker push') {
            steps {
                script {
                    echo "usando libraries -Pushear a dockerhub image with version: 1.0.0-${BUILD_ID}"
                    dockerLib.push(DockerImage: "rdiosalf/jenkinscaos:1.0.0-${BUILD_ID}")
                }
            }
        }
/*         stage('docker run') {
            steps {
                script {
                    dockerLib.run(DockerImage: "rdiosalf/jenkinscaos:1.0.0-${BUILD_ID}")
                }
            }

        } */
    }
}